[package]
name = "near-plugins-derive"
version = "0.1.0"
authors = ["Marcelo Fornet <marcelo@aurora.dev>"]
edition = "2018"
license = "CC0-1.0"
readme = "README.md"
description = """
Plugin system to extend NEAR contracts using macros.
"""

[lib]
proc-macro = true

[dependencies]
darling = "0.13.1"
proc-macro2 = "1.0"
quote = "1.0.9"
syn = { version = "1.0.69", features = ["full"] }
proc-macro-crate = "0.1.5"
