[package]
name = "near-plugins"
version = "0.1.0"
authors = ["Marcelo Fornet <marcelo@aurora.dev>"]
edition = "2018"
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/aurora-is-near/near-plugins"
homepage = "https://github.com/aurora-is-near/near-plugins"
description = """
Plugin system to extend NEAR contracts easily.
"""
keywords = ["near", "smart contract", "plugin"]

[lib]
crate-type = ["cdylib", "rlib"]
# proc-macro = true

[dependencies]
near-sdk = "4.0.0-pre.5"
near-plugins-derive = { path = "../near-plugins-derive", version = "0.1.0" }
serde = "1"

[dev-dependencies]
borsh = "0.9"
